image: nixos/latest

oauth: pages.sr.ht/PAGES:RW

submitter:
  git.sr.ht:
    enabled: true
    allow-refs:
      - refs/heads/trunk
      - "refs/tags/*"

sources:
  - https://git.sr.ht/~xqtc/zonsite

secrets:
  - 2e27eb3c-ee5e-40e4-a67d-f6c64b44a04f

environment:
  NIX_CONFIG: experimental-features = nix-command flakes
  site: tila.cat

tasks:
  - mirror: |
      echo "github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJlgithub.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=" >> ~/.ssh/known_hosts 2> /dev/null
      echo "github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=" >> ~/.ssh/known_hosts 2> /dev/null
      cd zonsite
      git remote add github git@github.com:xqtc161/zonsite.git
      git push --force github HEAD:trunk
      git push --force --tags github HEAD:trunk

  - build: |
      cd zonsite
      nix run .#build
      tar -czf ~/site.tar.gz -C zig-out .

  - upload: |
      nix run nixpkgs#hut -- pages publish -d $site ~/site.tar.gz
